#!/usr/bin/env python3
"""Import the Flutter app's drawing content into the web content bundle (PRD §9.6 content migration).

Exports lib/data/trace_items + lib/data/coloring_items from the FlexiKeys Flutter repo with Dart itself
(scripts/export_flutter_drawing_test.dart — the data uses helpers like ellipsePoints, so it can't be
parsed as text), then writes src/content/drawing/{trace,coloring}.json: same coordinates, same items,
so web and mobile draw the same letters and pictures. The exporter is copied into the Flutter repo's
test/ folder only for the run and removed afterwards. Needs the Flutter SDK.

    python3 scripts/import-flutter-drawing.py ~/Desktop/flexikeys    # path to the Flutter repo
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

# English names (the Flutter data has Uzbek labels + Russian ruLabel only).
EN = {
    "Uy": "House", "Yurak": "Heart", "Yulduz": "Star",
    "Banan": "Banana", "Gilos": "Cherries", "Olma": "Apple", "Apelsin": "Orange",
    "Mushuk": "Cat", "Quyon": "Rabbit", "Baliq": "Fish",
    "Mashina": "Car", "Avtobus": "Bus", "Samolyot": "Airplane",
    "Gul": "Flower", "Daraxt": "Tree", "Quyosh": "Sun",
}


def r(v):  # 0-1 coordinates: 4 decimals; pixel coordinates: 1
    if isinstance(v, list):
        return [r(x) for x in v]
    if isinstance(v, float):
        return round(v, 4) if abs(v) <= 2 else round(v, 1)
    return v


def named(item: dict) -> dict:
    lab, ru = item.pop("label"), item.pop("ruLabel")
    if ru:  # a word (object / picture), not a universal glyph
        return {"id": EN[lab].lower(), "names": {"uz": lab, "ru": ru, "en": EN[lab]}, **item}
    return {"label": lab, **item}


def main() -> None:
    flutter_repo = Path(sys.argv[1] if len(sys.argv) > 1 else "../../../flexikeys").resolve()
    here = Path(__file__).resolve().parent
    out_dir = here.parent / "src/content/drawing"
    tmp_test = flutter_repo / "test" / "_fk_web_drawing_export_test.dart"
    with tempfile.TemporaryDirectory() as tmp:
        raw = Path(tmp) / "drawing.json"
        shutil.copy(here / "export_flutter_drawing_test.dart", tmp_test)
        try:
            subprocess.run(
                ["flutter", "test", str(tmp_test.relative_to(flutter_repo))],
                cwd=flutter_repo, check=True, env={**os.environ, "FK_DRAWING_OUT": str(raw)},
                stdout=subprocess.DEVNULL,
            )
        finally:
            tmp_test.unlink(missing_ok=True)
        data = json.loads(raw.read_text("utf-8"))
    note = "GENERATED by scripts/import-flutter-drawing.py from the Flutter app's lib/data — do not edit by hand."
    for kind in ("trace", "coloring"):
        sets = {}
        for name, items in data[kind].items():
            cleaned = []
            for it in items:
                it = {k: r(v) for k, v in it.items()}
                for el in it.get("elements", []):
                    for k in list(el):
                        el[k] = r(el[k])
                    if el["model"] != "stroke":
                        el.pop("width")  # only strokes have a width
                    if el["smooth"]:
                        el.pop("smooth")
                cleaned.append(named(it))
            sets[name] = cleaned
        (out_dir / f"{kind}.json").write_text(
            json.dumps({"_": note, **sets}, ensure_ascii=False, separators=(",", ":")) + "\n", "utf-8"
        )
        print(kind, {k: len(v) for k, v in sets.items()})


if __name__ == "__main__":
    main()
